//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Basketitem
    {
        public int id_basketitem { get; set; }
        public Nullable<int> id_basket { get; set; }
        public Nullable<int> id_product { get; set; }
        public int qty_basketitem { get; set; }

        public int price_basketitem { get; set; }

        public virtual T_Basket T_Basket { get; set; }
        public virtual T_Product T_Product { get; set; }

        public static List<T_Basketitem> basketitemList;
        public static List<T_Product> basketProductList;

        public static int id_activeBasket { get; set; }
    }
}
