//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Order
    {
        public int id_order { get; set; }
        public Nullable<int> id_basket { get; set; }
        public string request_order { get; set; }
        public string comment_order { get; set; }
        public string filepath_order { get; set; }
        public string status_order { get; set; }
    
        public virtual T_Basket T_Basket { get; set; }
    }
}
