//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Product()
        {
            this.T_Basketitem = new HashSet<T_Basketitem>();
        }
    
        public int id_product { get; set; }
        public string name_product { get; set; }
        public int qty_product { get; set; }
        public string color_product { get; set; }
        public int price_product { get; set; }
        public string desc_product { get; set; }
        public Nullable<int> id_imgproduct { get; set; }
        public string type_product { get; set; }
        public Nullable<double> height_product { get; set; }
        public Nullable<double> lenght_product { get; set; }
        public Nullable<double> width_product { get; set; }
        public string path_imgproduct { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Basketitem> T_Basketitem { get; set; }
        public virtual T_Imgproduct T_Imgproduct { get; set; }

        public static List<T_Product> productList { get; set; }

        public static List<T_Product> productActive { get; set; }


        public int total_basketitem { get; set; }
    }
}
