//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
namespace v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_User()
        {
            this.T_Basket = new HashSet<T_Basket>();
        }
    
        public int id_user { get; set; }
        public string name_user { get; set; }
        public string firstname_user { get; set; }
        public int type_user { get; set; }

        [DisplayName("Adresse Mail")]
        [Required(ErrorMessage = "Merci de renseigner votre mail")]
        public string mail_user { get; set; }
        public Nullable<int> age_user { get; set; }
        public string adress_user { get; set; }
        public int tel_user { get; set; }

        [DisplayName("Mot de passe")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Merci de renseigner votre mot de passe")]
        public string pword_user { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Basket> T_Basket { get; set; }

        public string loginErrorMessage { get; set; }
    }
}
